/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.orvyl.sample.swf.checkout.activities.api;

import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.ActivitiesClient;
import com.amazonaws.services.simpleworkflow.flow.ActivitySchedulingOptions;

/**
 * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities}. 
 * Used to invoke activities asynchronously from workflow code.
 */
public interface CheckoutActivitiesClient extends ActivitiesClient
{

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#verifyOrder}
     */
    Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Order> verifyOrder(com.orvyl.sample.swf.checkout.activities.api.domain.Order order);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#verifyOrder}
     */
    Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Order> verifyOrder(com.orvyl.sample.swf.checkout.activities.api.domain.Order order, Promise<?>... waitFor);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#verifyOrder}
     */
    Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Order> verifyOrder(com.orvyl.sample.swf.checkout.activities.api.domain.Order order, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#verifyOrder}
     */
    Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Order> verifyOrder(Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Order> order);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#verifyOrder}
     */
    Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Order> verifyOrder(Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Order> order, Promise<?>... waitFor);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#verifyOrder}
     */
    Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Order> verifyOrder(Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Order> order, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#chargeCreditCard}
     */
    Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Receipt> chargeCreditCard(com.orvyl.sample.swf.checkout.activities.api.domain.Order order);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#chargeCreditCard}
     */
    Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Receipt> chargeCreditCard(com.orvyl.sample.swf.checkout.activities.api.domain.Order order, Promise<?>... waitFor);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#chargeCreditCard}
     */
    Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Receipt> chargeCreditCard(com.orvyl.sample.swf.checkout.activities.api.domain.Order order, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#chargeCreditCard}
     */
    Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Receipt> chargeCreditCard(Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Order> order);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#chargeCreditCard}
     */
    Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Receipt> chargeCreditCard(Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Order> order, Promise<?>... waitFor);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#chargeCreditCard}
     */
    Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Receipt> chargeCreditCard(Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Order> order, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#shipOrder}
     */
    Promise<com.orvyl.sample.swf.checkout.activities.api.domain.ShipOrderTxn> shipOrder(com.orvyl.sample.swf.checkout.activities.api.domain.Order order);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#shipOrder}
     */
    Promise<com.orvyl.sample.swf.checkout.activities.api.domain.ShipOrderTxn> shipOrder(com.orvyl.sample.swf.checkout.activities.api.domain.Order order, Promise<?>... waitFor);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#shipOrder}
     */
    Promise<com.orvyl.sample.swf.checkout.activities.api.domain.ShipOrderTxn> shipOrder(com.orvyl.sample.swf.checkout.activities.api.domain.Order order, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#shipOrder}
     */
    Promise<com.orvyl.sample.swf.checkout.activities.api.domain.ShipOrderTxn> shipOrder(Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Order> order);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#shipOrder}
     */
    Promise<com.orvyl.sample.swf.checkout.activities.api.domain.ShipOrderTxn> shipOrder(Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Order> order, Promise<?>... waitFor);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#shipOrder}
     */
    Promise<com.orvyl.sample.swf.checkout.activities.api.domain.ShipOrderTxn> shipOrder(Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Order> order, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#recordCompletion}
     */
    Promise<Void> recordCompletion(com.orvyl.sample.swf.checkout.activities.api.domain.Order order, com.orvyl.sample.swf.checkout.activities.api.domain.Receipt receipt, com.orvyl.sample.swf.checkout.activities.api.domain.ShipOrderTxn shipOrderTxn);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#recordCompletion}
     */
    Promise<Void> recordCompletion(com.orvyl.sample.swf.checkout.activities.api.domain.Order order, com.orvyl.sample.swf.checkout.activities.api.domain.Receipt receipt, com.orvyl.sample.swf.checkout.activities.api.domain.ShipOrderTxn shipOrderTxn, Promise<?>... waitFor);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#recordCompletion}
     */
    Promise<Void> recordCompletion(com.orvyl.sample.swf.checkout.activities.api.domain.Order order, com.orvyl.sample.swf.checkout.activities.api.domain.Receipt receipt, com.orvyl.sample.swf.checkout.activities.api.domain.ShipOrderTxn shipOrderTxn, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#recordCompletion}
     */
    Promise<Void> recordCompletion(Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Order> order, Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Receipt> receipt, Promise<com.orvyl.sample.swf.checkout.activities.api.domain.ShipOrderTxn> shipOrderTxn);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#recordCompletion}
     */
    Promise<Void> recordCompletion(Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Order> order, Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Receipt> receipt, Promise<com.orvyl.sample.swf.checkout.activities.api.domain.ShipOrderTxn> shipOrderTxn, Promise<?>... waitFor);

    /**
     * Generated from {@link com.orvyl.sample.swf.checkout.activities.api.CheckoutActivities#recordCompletion}
     */
    Promise<Void> recordCompletion(Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Order> order, Promise<com.orvyl.sample.swf.checkout.activities.api.domain.Receipt> receipt, Promise<com.orvyl.sample.swf.checkout.activities.api.domain.ShipOrderTxn> shipOrderTxn, ActivitySchedulingOptions optionsOverride, Promise<?>... waitFor);

}